+++
title = "About"
+++

## About Me

{{< figure class="avatar" src="/avatar.jpg" >}}

Welcome to my website. I am Brayden Noh and attend Auburn High School. I have pursued research projects in fields of electrochemistry and power control in high school  

## Research Interest

My interest is in interdisciplinary research in chemistry and automobile engineering. From 2018 to 2020, I have developed graphene dispersion supercapacitors for optimal uses in electric vehicles. Currently, I am developing a power selection algorithm for supercapacitor hybrid electric vehicles. 

## Publications

In chronological order:
1. Fabrication and empirical analysis of graphene dispersion/activated carbon on conductive networks in porous graphite felt supercapacitor, Elsevier Journal of Energy Storage
2. Design of Supercapacitor-Battery Hybrid Powertrain System with Pulse Width Modulation and Series Configuration for Light Electric Vehicles, SAE International Journal of Electrified Vehicles
3. Supercapacitor Assisted Hybrid Electric Vehicle Powertrain and Power Selection using Fuzzy Rule-Based Algorithm, IEEE AEIT 2020

## Awards

Year | Award | Category
-----|-------|--------
2020 | ISEF  | Finalist
2020 | Scholastic | Silver Medal in Fashion
2019 | ISEF  | Grand Award of 2nd Place in Energy, Chemical
2019 | ISEF  | Finalist
2018 | ISEF  | Finalist
2018 | ASEF  | Best of Fair

---

This is my [Medium Blog](https://3rayd8n.medium.com/).

> remoteness from reality is risky - arendt

## Past Advisors

* Jiangfeng Zhang: Department of Automotive Engineering, Clemson University

